import { supabase } from './supabase';
import { OPPORTUNITY_IDS, ACCOUNT_IDS, USER_IDS } from './seedIds';

export const seedOpportunities = async () => {
  const opportunities = [
    { id: OPPORTUNITY_IDS.o1, name: 'BDx 50 MW DPPA - Phase 1', linked_account_id: ACCOUNT_IDS.a1, value: 45000000, stage: 'Negotiation', priority: 'High', owner_id: USER_IDS.u1, next_action: 'Final pricing review', next_action_date: '2024-12-05', clickup_link: 'https://app.clickup.com/t/opp001', notes: 'Strong momentum', company_name: 'BDx Data Centers', highest_manager_known: 'CEO', industry: 'Data Center', monthly_bill: 2500000, target_capacity: 50, re_type: 'Solar - Ground', bess: true, profitability_rating: 5, target_decision_date: '2024-12-15' },
    { id: OPPORTUNITY_IDS.o2, name: 'Vardhman 31.5 MWp Phase 1', linked_account_id: ACCOUNT_IDS.a2, value: 28000000, stage: 'Proposal', priority: 'High', owner_id: USER_IDS.u3, next_action: 'Submit revised proposal', next_action_date: '2024-12-03', clickup_link: 'https://app.clickup.com/t/opp002', company_name: 'Vardhman Textiles', highest_manager_known: 'CFO', industry: 'Textile', monthly_bill: 1800000, target_capacity: 31.5, re_type: 'Solar - Rooftop', bess: false, profitability_rating: 4, target_decision_date: '2024-12-20' },
    { id: OPPORTUNITY_IDS.o3, name: 'Vinamilk Rooftop 5MW', linked_account_id: ACCOUNT_IDS.a3, value: 4500000, stage: 'Qualified', priority: 'Medium', owner_id: USER_IDS.u2, next_action: 'Site survey scheduling', next_action_date: '2024-12-10', company_name: 'Vinamilk', highest_manager_known: 'Energy Manager', industry: 'Food', monthly_bill: 450000, target_capacity: 5, re_type: 'Solar - Rooftop', bess: false, profitability_rating: 3 },
    { id: OPPORTUNITY_IDS.o4, name: 'SM Supermalls 15 Sites', linked_account_id: ACCOUNT_IDS.a4, value: 35000000, stage: 'Proposal', priority: 'High', owner_id: USER_IDS.u5, next_action: 'Present to board', next_action_date: '2024-12-08', clickup_link: 'https://app.clickup.com/t/opp004', company_name: 'SM Supermalls', highest_manager_known: 'Procurement Director', industry: 'Retail', monthly_bill: 3200000, target_capacity: 45, re_type: 'Solar - Rooftop', bess: true, profitability_rating: 4, target_decision_date: '2025-01-15' },
    { id: OPPORTUNITY_IDS.o5, name: 'PTT GC Industrial 20MW', linked_account_id: ACCOUNT_IDS.a5, value: 18000000, stage: 'Prospect', priority: 'Medium', owner_id: USER_IDS.u6, next_action: 'Initial meeting', next_action_date: '2024-12-12', company_name: 'PTT Global Chemical', highest_manager_known: 'Plant Manager', industry: 'Chemical', monthly_bill: 1500000, target_capacity: 20, re_type: 'Solar - Ground', bess: false, profitability_rating: 3 },
    { id: OPPORTUNITY_IDS.o6, name: 'Foxconn Vietnam 25MW', linked_account_id: ACCOUNT_IDS.a7, value: 22000000, stage: 'Negotiation', priority: 'High', owner_id: USER_IDS.u1, next_action: 'Contract review', next_action_date: '2024-12-04', clickup_link: 'https://app.clickup.com/t/opp006', company_name: 'Foxconn Vietnam', highest_manager_known: 'Country Director', industry: 'Manufacturing', monthly_bill: 2100000, target_capacity: 25, re_type: 'Solar - Rooftop', bess: true, profitability_rating: 5, target_decision_date: '2024-12-10' },
    { id: OPPORTUNITY_IDS.o7, name: 'Central Retail Bangkok 10MW', linked_account_id: ACCOUNT_IDS.a8, value: 9000000, stage: 'Qualified', priority: 'Medium', owner_id: USER_IDS.u6, next_action: 'Technical assessment', next_action_date: '2024-12-15', company_name: 'Central Retail', highest_manager_known: 'Sustainability Lead', industry: 'Retail', monthly_bill: 800000, target_capacity: 10, re_type: 'Solar - Rooftop', bess: false, profitability_rating: 3 },
    { id: OPPORTUNITY_IDS.o8, name: 'Mahindra Campus 2MW', linked_account_id: ACCOUNT_IDS.a6, value: 1800000, stage: 'Prospect', priority: 'Low', owner_id: USER_IDS.u3, next_action: 'Initial discussion', next_action_date: '2024-12-20', company_name: 'Mahindra University', highest_manager_known: 'Facilities Head', industry: 'Education', monthly_bill: 150000, target_capacity: 2, re_type: 'Solar - Rooftop', bess: false, profitability_rating: 2 },
    { id: OPPORTUNITY_IDS.o9, name: 'Vinamilk Expansion 8MW', linked_account_id: ACCOUNT_IDS.a3, value: 7200000, stage: 'Prospect', priority: 'Medium', owner_id: USER_IDS.u2, next_action: 'Follow-up meeting', next_action_date: '2024-12-18', company_name: 'Vinamilk', highest_manager_known: 'Energy Manager', industry: 'Food', monthly_bill: 650000, target_capacity: 8, re_type: 'Solar - Ground', bess: true, profitability_rating: 4 },
    { id: OPPORTUNITY_IDS.o10, name: 'SM North EDSA 5MW', linked_account_id: ACCOUNT_IDS.a4, value: 4500000, stage: 'Qualified', priority: 'High', owner_id: USER_IDS.u5, next_action: 'Site survey', next_action_date: '2024-12-11', company_name: 'SM Supermalls', highest_manager_known: 'Operations Manager', industry: 'Retail', monthly_bill: 420000, target_capacity: 5, re_type: 'Solar - Rooftop', bess: false, profitability_rating: 4 },
  ];
  const { error } = await supabase.from('opportunities').upsert(opportunities, { onConflict: 'id' });
  if (error) throw error;
  return opportunities.length;
};
